### ISSUE TITLE
Raw data available?

### ISSUE THREAD

**Issue by ProgramItUp** [kendricktan/suiron#2]
Nice work!

Thanks for sharing - great project.
Are you willing to share the raw data you collected?  

After reading about the project at
[](http://jabelone.com.au/blog/make-autonomous-car-code-included/) 

> In reality, 20 minutes is no where near enough data.  It works great on this particular track with similar lighting conditions but would likely fail if the conditions changed to much.

Your project is inspiring, I'd like to build a car myself.  Before doing that I'd like to try out try some different training ideas but need raw data.  If you ware willing to share your dataset it would be a real time saver.  My guess is others would appreciate it as well.

Thanks,

**Comment by patrickpoirier51** [comment]
Yes,  Nice work indeed, and getting access to raw data could as well establish a baseline so we can compare our different approach and associated performance.

**Comment by kendricktan** [comment]
Hi @ProgramItUp and @patrickpoirier51 thanks for taking interest into this project.

### [raw data download](https://www.dropbox.com/sh/3k65pft7gd4krhu/AABUJ9oJeOft1zZyDQbZ7l6aa?dl=0)

#### Before you start training there's a couple of stuff you need to do
1. Make a folder called `data` in the project root folder and put the downloaded raw_data into there
2. Replace `line 16` in `train.py` with `DATA_FILES = ['data/output_0.csv', 'data/output_1.csv']`
3. run `python train.py`
   - Keep training until the `loss` of the CNN reaches an asymptotic value

Have fun!

(Training on a GTX 760 took me around 5 hours)

**Comment by ProgramItUp** [comment]
Thanks.  I'm looking forward to giving it a try.
